events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;
    server_name _;

    add_header Access-Control-Allow-Origin * always;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;

    location / {
      root /usr/share/nginx/html;
      autoindex on;
      types {
        application/vnd.apple.mpegurl m3u8;
        video/mp2t ts;
        video/mp4 mp4 m4s;
      }
    }
  }
}
